version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - "3100:3000"
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules